name: dartray
version: 0.0.1
author: Brendan Duncan <brendanduncan@gmail.com>
description: DartRay is an extendable physically based ray tracer providing a number of state-of-the-art algorithms for rendering, lighting and shading. It is a port of the PBRT renderer.
homepage: https://github.com/brendan-duncan/dartray
documentation: https://github.com/brendan-duncan/dartray/wiki
dependencies:
  archive: '>=1.0.16'
  image: '>=1.1.19'
dev_dependencies:
  args: any
  crypto: any
