name: dartray
version: 0.0.2
author: Brendan Duncan <brendanduncan@gmail.com>
description: DartRay is an extendable physically based ray tracer providing a number of state-of-the-art algorithms for rendering, lighting and shading. It is a port of the PBRT renderer.
homepage: https://github.com/brendan-duncan/dartray
documentation: https://github.com/brendan-duncan/dartray/wiki
dependencies:
  archive: '>=2.0.0 <3.0.0'
  image: '>=2.0.0 <3.0.0'
dev_dependencies:
  args: any
  crypto: any
  build_runner: '>=0.8.10 <0.10.0'
  build_web_compilers: '>=0.3.6 <0.5.0'

