name: dartray
version: 0.0.1
author: Brendan Duncan <brendanduncan@gmail.com>
description: Dart port of the PBRT renderer
dev_dependencies:
  args: any
  image:
    git: https://github.com/brendan-duncan/image
